# Generated by Django 4.2.4 on 2023-10-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_slug', models.SlugField(unique=True)),
                ('product_img', models.ImageField(upload_to='picture')),
                ('product_price', models.IntegerField(default=0)),
                ('product_description', models.TextField(null=True)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_is_available', models.BooleanField(default=False)),
                ('product_modified_date', models.DateTimeField(auto_now_add=True)),
                ('product_expiry_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_pharmacy.category')),
            ],
        ),
    ]
