# Generated by Django 4.2.4 on 2023-11-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_token_alter_doctors_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.doctors'),
        ),
    ]
