# Generated by Django 4.2.4 on 2023-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_token_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='doctor',
        ),
    ]
