# Generated by Django 4.2.4 on 2023-11-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_token_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.departments'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.token'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointments.departments'),
        ),
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
